# application.properties를 application.yml로 변경후 아래와 같이 코드를 입력합니다
# Tip)
# application.properties를 사용하셔도 무방합니다만, 굳이 yml로 변경한 이유는 properties에 비해 상대적으로 유연한 구조를 가졌기 때문입니다.
# yml은 상위 계층에 대한 표현, List 등을 완전하게 표현할수가 있습니다.
# 최근의 많은 도구들이 yml 설정을 지원하기 때문에 이참에 시작해보시는 것을 추천드립니다.

# http://localhost:8080/h2-console
#server:
#  port: 8082  # Spring boot Server port

spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  datasource:
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  config :
    activate :
      on-profile : local

#  datasource:
#    driver-class-name: org.h2.Driver  #h2 드라이버 설정
#    url: jdbc:h2:file:~/Develop/restAPI  #접속 URL
#    username: test  # 사용자 이름 (로그인 시 사용)
#    password: 1234  # 사용자 암호 (로그인 시 사용)